// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2MKsoXgJfNOywfWaz28GDgi5iOFSLY4',
    appId: '1:477859859729:web:6d673a1ef2de779b0910b0',
    messagingSenderId: '477859859729',
    projectId: 'ecommerceapp-62b5b',
    authDomain: 'ecommerceapp-62b5b.firebaseapp.com',
    storageBucket: 'ecommerceapp-62b5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVLFha7WLfw3iJhAnYFHYEKVCsm3AqvZI',
    appId: '1:477859859729:android:cd3514e82d05e7c10910b0',
    messagingSenderId: '477859859729',
    projectId: 'ecommerceapp-62b5b',
    storageBucket: 'ecommerceapp-62b5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7tbwO1IgDaF6eayH4lXYa0KTTlYOqoos',
    appId: '1:477859859729:ios:aa8b81149d4a9c3e0910b0',
    messagingSenderId: '477859859729',
    projectId: 'ecommerceapp-62b5b',
    storageBucket: 'ecommerceapp-62b5b.appspot.com',
    iosClientId: '477859859729-d3fsdohrv3b0aqrmgtc8mttvs1fkmkhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7tbwO1IgDaF6eayH4lXYa0KTTlYOqoos',
    appId: '1:477859859729:ios:aa8b81149d4a9c3e0910b0',
    messagingSenderId: '477859859729',
    projectId: 'ecommerceapp-62b5b',
    storageBucket: 'ecommerceapp-62b5b.appspot.com',
    iosClientId: '477859859729-d3fsdohrv3b0aqrmgtc8mttvs1fkmkhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
